[package]
name = "rust_math_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_math_lib"
path = "src/fib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]